# используем язык Java. Travis CI поддерживает также и другие языки
language: java
# используем режим обычного пользователя для сборки проекта
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику JaCoCo
# здесь используется сторонний сервис htpps://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# env:
#   global:
#    - CODECOV_TOKEN='e6fcd080-e68f-4b74-9d79-a654670302a4'

# отправлять уведомление на почту, если сборка упала
notifications:
  email:
    recipients:
      - bezngor@gmail.com
    on_success: never
    on_failure: always